### ISSUE TITLE
missing sumatra.bat

### ISSUE THREAD

**Issue by LutzHas** [luigiScarso/context-npp#1]
Hi Luigi,

I tried to install the ConTeXt plugin because I want to use the rtl capabilities of Notepad++ for hebrew script.
I didn't found the sumatra.bat in /scripts, or am I missing something?

Greetings Lutz

**Comment by luigiScarso** [comment]
Than you, just added under 
context-npp/install/Npp-for-ConTeXt/scripts

**Comment by LutzHas** [comment]
Thanks, works now as expected.
